services:
  fintual-api:
    build: .
    image: fintual-api:test
    container_name: fintual-api-local
    env_file:
      - path: .env
        format: raw
    volumes:
      - ./.env:/app/.env
      - ./tmp:/app/tmp
    ports:
      - "3000:3000"
    command: ["sleep", "infinity"]
    restart: unless-stopped
